export default {
    CHANGE_BLOG_LOADING: 'CHANGE_BLOG_LOADING',
    START_FETCH_BLOG_LIST: 'START_BLOG_LIST',
    FETCH_BLOG_LIST_SUCCESS: 'FETCH_BLOG_LIST_SUCCESS',
    FETCH_BLOG_LIST_FAILED: 'FETCH_BLOG_LIST_FAILED'
}