export { default as Home } from './Home'
export { default as Articl } from './Articl'
export { default as Users } from './Users'
export { default as ArticlDetail } from './Articl/ArticlDetail'
export { default as NotFound } from './NotFound'