export default {
   NOTICECENTER_CHANGE_HASREAD: 'NOTICECENTER_CHANGE_HASREAD',
   ALL_HASREAD_CHANGE: 'ALL_HASREAD_CHANGE',
   START_NOTICE_FETCH: 'START_NOTICE_FETCH',
   FINISH_NOTICE_FETCH: 'FINISH_NOTICE_FETCH',
   SAVE_NOTICE: 'SAVE_NOTICE',
   START_LOGIN: 'START_LOGIN',
   LOGIN_SUCCESS: 'LOGIN_SUCCESS',
   LOGIN_FAILED: 'LOGIN_FAILED'
}