export default {
   // CHANGE_BLOG_LOADING: 'CHANGE_BLOG_LOADING',
   START_BLOG_LIST_FETCH: 'START_BLOG_LIST_FETCH',
   FETCH_SUCCESS_BLOG_LIST: 'FETCH_SUCCESS_BLOG_LIST',
   FETCH_FAILED_BLOG_LIST: 'FETCH_FAILED_BLOG_LIST',
}